// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"regexp"

	"github.com/go-telegram/bot"
	"github.com/go-telegram/bot/models"
	"github.com/ofstudio/voxify/pkg/telegram"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBot creates a new instance of MockBot. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBot(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBot {
	mock := &MockBot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBot is an autogenerated mock type for the Bot type
type MockBot struct {
	mock.Mock
}

type MockBot_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBot) EXPECT() *MockBot_Expecter {
	return &MockBot_Expecter{mock: &_m.Mock}
}

// ID provides a mock function for the type MockBot
func (_mock *MockBot) ID() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockBot_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBot_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBot_Expecter) ID() *MockBot_ID_Call {
	return &MockBot_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBot_ID_Call) Run(run func()) *MockBot_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBot_ID_Call) Return(n int64) *MockBot_ID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockBot_ID_Call) RunAndReturn(run func() int64) *MockBot_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessUpdate provides a mock function for the type MockBot
func (_mock *MockBot) ProcessUpdate(ctx context.Context, upd *models.Update) {
	_mock.Called(ctx, upd)
	return
}

// MockBot_ProcessUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessUpdate'
type MockBot_ProcessUpdate_Call struct {
	*mock.Call
}

// ProcessUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - upd *models.Update
func (_e *MockBot_Expecter) ProcessUpdate(ctx interface{}, upd interface{}) *MockBot_ProcessUpdate_Call {
	return &MockBot_ProcessUpdate_Call{Call: _e.mock.On("ProcessUpdate", ctx, upd)}
}

func (_c *MockBot_ProcessUpdate_Call) Run(run func(ctx context.Context, upd *models.Update)) *MockBot_ProcessUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Update
		if args[1] != nil {
			arg1 = args[1].(*models.Update)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_ProcessUpdate_Call) Return() *MockBot_ProcessUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBot_ProcessUpdate_Call) RunAndReturn(run func(ctx context.Context, upd *models.Update)) *MockBot_ProcessUpdate_Call {
	_c.Run(run)
	return _c
}

// RegisterHandler provides a mock function for the type MockBot
func (_mock *MockBot) RegisterHandler(handlerType bot.HandlerType, pattern string, matchType bot.MatchType, f telegram.HandlerFunc, m ...telegram.Middleware) string {
	var tmpRet mock.Arguments
	if len(m) > 0 {
		tmpRet = _mock.Called(handlerType, pattern, matchType, f, m)
	} else {
		tmpRet = _mock.Called(handlerType, pattern, matchType, f)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RegisterHandler")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(bot.HandlerType, string, bot.MatchType, telegram.HandlerFunc, ...telegram.Middleware) string); ok {
		r0 = returnFunc(handlerType, pattern, matchType, f, m...)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBot_RegisterHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHandler'
type MockBot_RegisterHandler_Call struct {
	*mock.Call
}

// RegisterHandler is a helper method to define mock.On call
//   - handlerType bot.HandlerType
//   - pattern string
//   - matchType bot.MatchType
//   - f telegram.HandlerFunc
//   - m ...telegram.Middleware
func (_e *MockBot_Expecter) RegisterHandler(handlerType interface{}, pattern interface{}, matchType interface{}, f interface{}, m ...interface{}) *MockBot_RegisterHandler_Call {
	return &MockBot_RegisterHandler_Call{Call: _e.mock.On("RegisterHandler",
		append([]interface{}{handlerType, pattern, matchType, f}, m...)...)}
}

func (_c *MockBot_RegisterHandler_Call) Run(run func(handlerType bot.HandlerType, pattern string, matchType bot.MatchType, f telegram.HandlerFunc, m ...telegram.Middleware)) *MockBot_RegisterHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bot.HandlerType
		if args[0] != nil {
			arg0 = args[0].(bot.HandlerType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bot.MatchType
		if args[2] != nil {
			arg2 = args[2].(bot.MatchType)
		}
		var arg3 telegram.HandlerFunc
		if args[3] != nil {
			arg3 = args[3].(telegram.HandlerFunc)
		}
		var arg4 []telegram.Middleware
		var variadicArgs []telegram.Middleware
		if len(args) > 4 {
			variadicArgs = args[4].([]telegram.Middleware)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockBot_RegisterHandler_Call) Return(s string) *MockBot_RegisterHandler_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBot_RegisterHandler_Call) RunAndReturn(run func(handlerType bot.HandlerType, pattern string, matchType bot.MatchType, f telegram.HandlerFunc, m ...telegram.Middleware) string) *MockBot_RegisterHandler_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterHandlerMatchFunc provides a mock function for the type MockBot
func (_mock *MockBot) RegisterHandlerMatchFunc(matchFunc bot.MatchFunc, f telegram.HandlerFunc, m ...telegram.Middleware) string {
	var tmpRet mock.Arguments
	if len(m) > 0 {
		tmpRet = _mock.Called(matchFunc, f, m)
	} else {
		tmpRet = _mock.Called(matchFunc, f)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RegisterHandlerMatchFunc")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(bot.MatchFunc, telegram.HandlerFunc, ...telegram.Middleware) string); ok {
		r0 = returnFunc(matchFunc, f, m...)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBot_RegisterHandlerMatchFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHandlerMatchFunc'
type MockBot_RegisterHandlerMatchFunc_Call struct {
	*mock.Call
}

// RegisterHandlerMatchFunc is a helper method to define mock.On call
//   - matchFunc bot.MatchFunc
//   - f telegram.HandlerFunc
//   - m ...telegram.Middleware
func (_e *MockBot_Expecter) RegisterHandlerMatchFunc(matchFunc interface{}, f interface{}, m ...interface{}) *MockBot_RegisterHandlerMatchFunc_Call {
	return &MockBot_RegisterHandlerMatchFunc_Call{Call: _e.mock.On("RegisterHandlerMatchFunc",
		append([]interface{}{matchFunc, f}, m...)...)}
}

func (_c *MockBot_RegisterHandlerMatchFunc_Call) Run(run func(matchFunc bot.MatchFunc, f telegram.HandlerFunc, m ...telegram.Middleware)) *MockBot_RegisterHandlerMatchFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bot.MatchFunc
		if args[0] != nil {
			arg0 = args[0].(bot.MatchFunc)
		}
		var arg1 telegram.HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(telegram.HandlerFunc)
		}
		var arg2 []telegram.Middleware
		var variadicArgs []telegram.Middleware
		if len(args) > 2 {
			variadicArgs = args[2].([]telegram.Middleware)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockBot_RegisterHandlerMatchFunc_Call) Return(s string) *MockBot_RegisterHandlerMatchFunc_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBot_RegisterHandlerMatchFunc_Call) RunAndReturn(run func(matchFunc bot.MatchFunc, f telegram.HandlerFunc, m ...telegram.Middleware) string) *MockBot_RegisterHandlerMatchFunc_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterHandlerRegexp provides a mock function for the type MockBot
func (_mock *MockBot) RegisterHandlerRegexp(handlerType bot.HandlerType, re *regexp.Regexp, f telegram.HandlerFunc, m ...telegram.Middleware) string {
	var tmpRet mock.Arguments
	if len(m) > 0 {
		tmpRet = _mock.Called(handlerType, re, f, m)
	} else {
		tmpRet = _mock.Called(handlerType, re, f)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RegisterHandlerRegexp")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(bot.HandlerType, *regexp.Regexp, telegram.HandlerFunc, ...telegram.Middleware) string); ok {
		r0 = returnFunc(handlerType, re, f, m...)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBot_RegisterHandlerRegexp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHandlerRegexp'
type MockBot_RegisterHandlerRegexp_Call struct {
	*mock.Call
}

// RegisterHandlerRegexp is a helper method to define mock.On call
//   - handlerType bot.HandlerType
//   - re *regexp.Regexp
//   - f telegram.HandlerFunc
//   - m ...telegram.Middleware
func (_e *MockBot_Expecter) RegisterHandlerRegexp(handlerType interface{}, re interface{}, f interface{}, m ...interface{}) *MockBot_RegisterHandlerRegexp_Call {
	return &MockBot_RegisterHandlerRegexp_Call{Call: _e.mock.On("RegisterHandlerRegexp",
		append([]interface{}{handlerType, re, f}, m...)...)}
}

func (_c *MockBot_RegisterHandlerRegexp_Call) Run(run func(handlerType bot.HandlerType, re *regexp.Regexp, f telegram.HandlerFunc, m ...telegram.Middleware)) *MockBot_RegisterHandlerRegexp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bot.HandlerType
		if args[0] != nil {
			arg0 = args[0].(bot.HandlerType)
		}
		var arg1 *regexp.Regexp
		if args[1] != nil {
			arg1 = args[1].(*regexp.Regexp)
		}
		var arg2 telegram.HandlerFunc
		if args[2] != nil {
			arg2 = args[2].(telegram.HandlerFunc)
		}
		var arg3 []telegram.Middleware
		var variadicArgs []telegram.Middleware
		if len(args) > 3 {
			variadicArgs = args[3].([]telegram.Middleware)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockBot_RegisterHandlerRegexp_Call) Return(s string) *MockBot_RegisterHandlerRegexp_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBot_RegisterHandlerRegexp_Call) RunAndReturn(run func(handlerType bot.HandlerType, re *regexp.Regexp, f telegram.HandlerFunc, m ...telegram.Middleware) string) *MockBot_RegisterHandlerRegexp_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockBot
func (_mock *MockBot) SendMessage(ctx context.Context, p *bot.SendMessageParams) (*models.Message, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *models.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bot.SendMessageParams) (*models.Message, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bot.SendMessageParams) *models.Message); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bot.SendMessageParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBot_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockBot_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - p *bot.SendMessageParams
func (_e *MockBot_Expecter) SendMessage(ctx interface{}, p interface{}) *MockBot_SendMessage_Call {
	return &MockBot_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, p)}
}

func (_c *MockBot_SendMessage_Call) Run(run func(ctx context.Context, p *bot.SendMessageParams)) *MockBot_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bot.SendMessageParams
		if args[1] != nil {
			arg1 = args[1].(*bot.SendMessageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_SendMessage_Call) Return(message *models.Message, err error) *MockBot_SendMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockBot_SendMessage_Call) RunAndReturn(run func(ctx context.Context, p *bot.SendMessageParams) (*models.Message, error)) *MockBot_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockBot
func (_mock *MockBot) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockBot_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockBot_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBot_Expecter) Start(ctx interface{}) *MockBot_Start_Call {
	return &MockBot_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockBot_Start_Call) Run(run func(ctx context.Context)) *MockBot_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBot_Start_Call) Return() *MockBot_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBot_Start_Call) RunAndReturn(run func(ctx context.Context)) *MockBot_Start_Call {
	_c.Run(run)
	return _c
}

// UnregisterHandler provides a mock function for the type MockBot
func (_mock *MockBot) UnregisterHandler(id string) {
	_mock.Called(id)
	return
}

// MockBot_UnregisterHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterHandler'
type MockBot_UnregisterHandler_Call struct {
	*mock.Call
}

// UnregisterHandler is a helper method to define mock.On call
//   - id string
func (_e *MockBot_Expecter) UnregisterHandler(id interface{}) *MockBot_UnregisterHandler_Call {
	return &MockBot_UnregisterHandler_Call{Call: _e.mock.On("UnregisterHandler", id)}
}

func (_c *MockBot_UnregisterHandler_Call) Run(run func(id string)) *MockBot_UnregisterHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBot_UnregisterHandler_Call) Return() *MockBot_UnregisterHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBot_UnregisterHandler_Call) RunAndReturn(run func(id string)) *MockBot_UnregisterHandler_Call {
	_c.Run(run)
	return _c
}
