// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ofstudio/voxify/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEpisodeDownloader creates a new instance of MockEpisodeDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEpisodeDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEpisodeDownloader {
	mock := &MockEpisodeDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEpisodeDownloader is an autogenerated mock type for the EpisodeDownloader type
type MockEpisodeDownloader struct {
	mock.Mock
}

type MockEpisodeDownloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEpisodeDownloader) EXPECT() *MockEpisodeDownloader_Expecter {
	return &MockEpisodeDownloader_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type MockEpisodeDownloader
func (_mock *MockEpisodeDownloader) Download(ctx context.Context, request domain.DownloadRequest) (*domain.Episode, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 *domain.Episode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DownloadRequest) (*domain.Episode, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DownloadRequest) *domain.Episode); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Episode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.DownloadRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEpisodeDownloader_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockEpisodeDownloader_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - request domain.DownloadRequest
func (_e *MockEpisodeDownloader_Expecter) Download(ctx interface{}, request interface{}) *MockEpisodeDownloader_Download_Call {
	return &MockEpisodeDownloader_Download_Call{Call: _e.mock.On("Download", ctx, request)}
}

func (_c *MockEpisodeDownloader_Download_Call) Run(run func(ctx context.Context, request domain.DownloadRequest)) *MockEpisodeDownloader_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DownloadRequest
		if args[1] != nil {
			arg1 = args[1].(domain.DownloadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEpisodeDownloader_Download_Call) Return(episode *domain.Episode, err error) *MockEpisodeDownloader_Download_Call {
	_c.Call.Return(episode, err)
	return _c
}

func (_c *MockEpisodeDownloader_Download_Call) RunAndReturn(run func(ctx context.Context, request domain.DownloadRequest) (*domain.Episode, error)) *MockEpisodeDownloader_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockEpisodeDownloader
func (_mock *MockEpisodeDownloader) Validate(ctx context.Context, request domain.DownloadRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DownloadRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEpisodeDownloader_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockEpisodeDownloader_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - request domain.DownloadRequest
func (_e *MockEpisodeDownloader_Expecter) Validate(ctx interface{}, request interface{}) *MockEpisodeDownloader_Validate_Call {
	return &MockEpisodeDownloader_Validate_Call{Call: _e.mock.On("Validate", ctx, request)}
}

func (_c *MockEpisodeDownloader_Validate_Call) Run(run func(ctx context.Context, request domain.DownloadRequest)) *MockEpisodeDownloader_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DownloadRequest
		if args[1] != nil {
			arg1 = args[1].(domain.DownloadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEpisodeDownloader_Validate_Call) Return(err error) *MockEpisodeDownloader_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEpisodeDownloader_Validate_Call) RunAndReturn(run func(ctx context.Context, request domain.DownloadRequest) error) *MockEpisodeDownloader_Validate_Call {
	_c.Call.Return(run)
	return _c
}
