// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ofstudio/voxify/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventBus creates a new instance of MockEventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventBus {
	mock := &MockEventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventBus is an autogenerated mock type for the EventBus type
type MockEventBus struct {
	mock.Mock
}

type MockEventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventBus) EXPECT() *MockEventBus_Expecter {
	return &MockEventBus_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockEventBus
func (_mock *MockEventBus) Publish(event domain.Event) {
	_mock.Called(event)
	return
}

// MockEventBus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventBus_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event domain.Event
func (_e *MockEventBus_Expecter) Publish(event interface{}) *MockEventBus_Publish_Call {
	return &MockEventBus_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *MockEventBus_Publish_Call) Run(run func(event domain.Event)) *MockEventBus_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Event
		if args[0] != nil {
			arg0 = args[0].(domain.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventBus_Publish_Call) Return() *MockEventBus_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventBus_Publish_Call) RunAndReturn(run func(event domain.Event)) *MockEventBus_Publish_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type MockEventBus
func (_mock *MockEventBus) Subscribe(eventType domain.EventType, handler domain.EventHandler) {
	_mock.Called(eventType, handler)
	return
}

// MockEventBus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventBus_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - eventType domain.EventType
//   - handler domain.EventHandler
func (_e *MockEventBus_Expecter) Subscribe(eventType interface{}, handler interface{}) *MockEventBus_Subscribe_Call {
	return &MockEventBus_Subscribe_Call{Call: _e.mock.On("Subscribe", eventType, handler)}
}

func (_c *MockEventBus_Subscribe_Call) Run(run func(eventType domain.EventType, handler domain.EventHandler)) *MockEventBus_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.EventType
		if args[0] != nil {
			arg0 = args[0].(domain.EventType)
		}
		var arg1 domain.EventHandler
		if args[1] != nil {
			arg1 = args[1].(domain.EventHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventBus_Subscribe_Call) Return() *MockEventBus_Subscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventBus_Subscribe_Call) RunAndReturn(run func(eventType domain.EventType, handler domain.EventHandler)) *MockEventBus_Subscribe_Call {
	_c.Run(run)
	return _c
}
