// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ofstudio/voxify/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFeedBuilder creates a new instance of MockFeedBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedBuilder {
	mock := &MockFeedBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeedBuilder is an autogenerated mock type for the FeedBuilder type
type MockFeedBuilder struct {
	mock.Mock
}

type MockFeedBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeedBuilder) EXPECT() *MockFeedBuilder_Expecter {
	return &MockFeedBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockFeedBuilder
func (_mock *MockFeedBuilder) Build(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFeedBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockFeedBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFeedBuilder_Expecter) Build(ctx interface{}) *MockFeedBuilder_Build_Call {
	return &MockFeedBuilder_Build_Call{Call: _e.mock.On("Build", ctx)}
}

func (_c *MockFeedBuilder_Build_Call) Run(run func(ctx context.Context)) *MockFeedBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFeedBuilder_Build_Call) Return(err error) *MockFeedBuilder_Build_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFeedBuilder_Build_Call) RunAndReturn(run func(ctx context.Context) error) *MockFeedBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockFeedBuilder
func (_mock *MockFeedBuilder) Info(ctx context.Context) (*domain.FeedInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 *domain.FeedInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*domain.FeedInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *domain.FeedInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FeedInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeedBuilder_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockFeedBuilder_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFeedBuilder_Expecter) Info(ctx interface{}) *MockFeedBuilder_Info_Call {
	return &MockFeedBuilder_Info_Call{Call: _e.mock.On("Info", ctx)}
}

func (_c *MockFeedBuilder_Info_Call) Run(run func(ctx context.Context)) *MockFeedBuilder_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFeedBuilder_Info_Call) Return(feedInfo *domain.FeedInfo, err error) *MockFeedBuilder_Info_Call {
	_c.Call.Return(feedInfo, err)
	return _c
}

func (_c *MockFeedBuilder_Info_Call) RunAndReturn(run func(ctx context.Context) (*domain.FeedInfo, error)) *MockFeedBuilder_Info_Call {
	_c.Call.Return(run)
	return _c
}
