// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ofstudio/voxify/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Notify() <-chan *entities.Process {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 <-chan *entities.Process
	if returnFunc, ok := ret.Get(0).(func() <-chan *entities.Process); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *entities.Process)
		}
	}
	return r0
}

// MockNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) Notify() *MockNotifier_Notify_Call {
	return &MockNotifier_Notify_Call{Call: _e.mock.On("Notify")}
}

func (_c *MockNotifier_Notify_Call) Run(run func()) *MockNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_Notify_Call) Return(processCh <-chan *entities.Process) *MockNotifier_Notify_Call {
	_c.Call.Return(processCh)
	return _c
}

func (_c *MockNotifier_Notify_Call) RunAndReturn(run func() <-chan *entities.Process) *MockNotifier_Notify_Call {
	_c.Call.Return(run)
	return _c
}
