// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ofstudio/voxify/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlatform creates a new instance of MockPlatform. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlatform(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlatform {
	mock := &MockPlatform{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlatform is an autogenerated mock type for the Platform type
type MockPlatform struct {
	mock.Mock
}

type MockPlatform_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlatform) EXPECT() *MockPlatform_Expecter {
	return &MockPlatform_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type MockPlatform
func (_mock *MockPlatform) Download(ctx context.Context, req entities.Request) (*entities.Episode, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 *entities.Episode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Request) (*entities.Episode, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Request) *entities.Episode); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Episode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockPlatform_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - req entities.Request
func (_e *MockPlatform_Expecter) Download(ctx interface{}, req interface{}) *MockPlatform_Download_Call {
	return &MockPlatform_Download_Call{Call: _e.mock.On("Download", ctx, req)}
}

func (_c *MockPlatform_Download_Call) Run(run func(ctx context.Context, req entities.Request)) *MockPlatform_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Request
		if args[1] != nil {
			arg1 = args[1].(entities.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_Download_Call) Return(episode *entities.Episode, err error) *MockPlatform_Download_Call {
	_c.Call.Return(episode, err)
	return _c
}

func (_c *MockPlatform_Download_Call) RunAndReturn(run func(ctx context.Context, req entities.Request) (*entities.Episode, error)) *MockPlatform_Download_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockPlatform
func (_mock *MockPlatform) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPlatform_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockPlatform_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockPlatform_Expecter) ID() *MockPlatform_ID_Call {
	return &MockPlatform_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockPlatform_ID_Call) Run(run func()) *MockPlatform_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlatform_ID_Call) Return(s string) *MockPlatform_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPlatform_ID_Call) RunAndReturn(run func() string) *MockPlatform_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockPlatform
func (_mock *MockPlatform) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockPlatform_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPlatform_Expecter) Init(ctx interface{}) *MockPlatform_Init_Call {
	return &MockPlatform_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockPlatform_Init_Call) Run(run func(ctx context.Context)) *MockPlatform_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatform_Init_Call) Return(err error) *MockPlatform_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockPlatform_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Match provides a mock function for the type MockPlatform
func (_mock *MockPlatform) Match(url string) bool {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(url)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPlatform_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockPlatform_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - url string
func (_e *MockPlatform_Expecter) Match(url interface{}) *MockPlatform_Match_Call {
	return &MockPlatform_Match_Call{Call: _e.mock.On("Match", url)}
}

func (_c *MockPlatform_Match_Call) Run(run func(url string)) *MockPlatform_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatform_Match_Call) Return(b bool) *MockPlatform_Match_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPlatform_Match_Call) RunAndReturn(run func(url string) bool) *MockPlatform_Match_Call {
	_c.Call.Return(run)
	return _c
}
