// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ofstudio/voxify/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockStore
func (_mock *MockStore) Begin(ctx context.Context) (domain.Store, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 domain.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.Store, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.Store); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockStore_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) Begin(ctx interface{}) *MockStore_Begin_Call {
	return &MockStore_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockStore_Begin_Call) Run(run func(ctx context.Context)) *MockStore_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Begin_Call) Return(store domain.Store, err error) *MockStore_Begin_Call {
	_c.Call.Return(store, err)
	return _c
}

func (_c *MockStore_Begin_Call) RunAndReturn(run func(ctx context.Context) (domain.Store, error)) *MockStore_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockStore
func (_mock *MockStore) Close() {
	_mock.Called()
	return
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return() *MockStore_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func()) *MockStore_Close_Call {
	_c.Run(run)
	return _c
}

// Commit provides a mock function for the type MockStore
func (_mock *MockStore) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockStore_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockStore_Expecter) Commit() *MockStore_Commit_Call {
	return &MockStore_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockStore_Commit_Call) Run(run func()) *MockStore_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Commit_Call) Return(err error) *MockStore_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Commit_Call) RunAndReturn(run func() error) *MockStore_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// EpisodeCount provides a mock function for the type MockStore
func (_mock *MockStore) EpisodeCount(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EpisodeCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_EpisodeCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EpisodeCount'
type MockStore_EpisodeCount_Call struct {
	*mock.Call
}

// EpisodeCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) EpisodeCount(ctx interface{}) *MockStore_EpisodeCount_Call {
	return &MockStore_EpisodeCount_Call{Call: _e.mock.On("EpisodeCount", ctx)}
}

func (_c *MockStore_EpisodeCount_Call) Run(run func(ctx context.Context)) *MockStore_EpisodeCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_EpisodeCount_Call) Return(n int, err error) *MockStore_EpisodeCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_EpisodeCount_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockStore_EpisodeCount_Call {
	_c.Call.Return(run)
	return _c
}

// EpisodeCreate provides a mock function for the type MockStore
func (_mock *MockStore) EpisodeCreate(ctx context.Context, episode *domain.Episode) error {
	ret := _mock.Called(ctx, episode)

	if len(ret) == 0 {
		panic("no return value specified for EpisodeCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Episode) error); ok {
		r0 = returnFunc(ctx, episode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_EpisodeCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EpisodeCreate'
type MockStore_EpisodeCreate_Call struct {
	*mock.Call
}

// EpisodeCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - episode *domain.Episode
func (_e *MockStore_Expecter) EpisodeCreate(ctx interface{}, episode interface{}) *MockStore_EpisodeCreate_Call {
	return &MockStore_EpisodeCreate_Call{Call: _e.mock.On("EpisodeCreate", ctx, episode)}
}

func (_c *MockStore_EpisodeCreate_Call) Run(run func(ctx context.Context, episode *domain.Episode)) *MockStore_EpisodeCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Episode
		if args[1] != nil {
			arg1 = args[1].(*domain.Episode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_EpisodeCreate_Call) Return(err error) *MockStore_EpisodeCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_EpisodeCreate_Call) RunAndReturn(run func(ctx context.Context, episode *domain.Episode) error) *MockStore_EpisodeCreate_Call {
	_c.Call.Return(run)
	return _c
}

// EpisodeGet provides a mock function for the type MockStore
func (_mock *MockStore) EpisodeGet(ctx context.Context, pageSize int, pageNumber int) ([]*domain.Episode, error) {
	ret := _mock.Called(ctx, pageSize, pageNumber)

	if len(ret) == 0 {
		panic("no return value specified for EpisodeGet")
	}

	var r0 []*domain.Episode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Episode, error)); ok {
		return returnFunc(ctx, pageSize, pageNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Episode); ok {
		r0 = returnFunc(ctx, pageSize, pageNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Episode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, pageSize, pageNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_EpisodeGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EpisodeGet'
type MockStore_EpisodeGet_Call struct {
	*mock.Call
}

// EpisodeGet is a helper method to define mock.On call
//   - ctx context.Context
//   - pageSize int
//   - pageNumber int
func (_e *MockStore_Expecter) EpisodeGet(ctx interface{}, pageSize interface{}, pageNumber interface{}) *MockStore_EpisodeGet_Call {
	return &MockStore_EpisodeGet_Call{Call: _e.mock.On("EpisodeGet", ctx, pageSize, pageNumber)}
}

func (_c *MockStore_EpisodeGet_Call) Run(run func(ctx context.Context, pageSize int, pageNumber int)) *MockStore_EpisodeGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_EpisodeGet_Call) Return(episodes []*domain.Episode, err error) *MockStore_EpisodeGet_Call {
	_c.Call.Return(episodes, err)
	return _c
}

func (_c *MockStore_EpisodeGet_Call) RunAndReturn(run func(ctx context.Context, pageSize int, pageNumber int) ([]*domain.Episode, error)) *MockStore_EpisodeGet_Call {
	_c.Call.Return(run)
	return _c
}

// EpisodeGetByUrl provides a mock function for the type MockStore
func (_mock *MockStore) EpisodeGetByUrl(ctx context.Context, url string) ([]*domain.Episode, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for EpisodeGetByUrl")
	}

	var r0 []*domain.Episode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Episode, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Episode); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Episode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_EpisodeGetByUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EpisodeGetByUrl'
type MockStore_EpisodeGetByUrl_Call struct {
	*mock.Call
}

// EpisodeGetByUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockStore_Expecter) EpisodeGetByUrl(ctx interface{}, url interface{}) *MockStore_EpisodeGetByUrl_Call {
	return &MockStore_EpisodeGetByUrl_Call{Call: _e.mock.On("EpisodeGetByUrl", ctx, url)}
}

func (_c *MockStore_EpisodeGetByUrl_Call) Run(run func(ctx context.Context, url string)) *MockStore_EpisodeGetByUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_EpisodeGetByUrl_Call) Return(episodes []*domain.Episode, err error) *MockStore_EpisodeGetByUrl_Call {
	_c.Call.Return(episodes, err)
	return _c
}

func (_c *MockStore_EpisodeGetByUrl_Call) RunAndReturn(run func(ctx context.Context, url string) ([]*domain.Episode, error)) *MockStore_EpisodeGetByUrl_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockStore
func (_mock *MockStore) Rollback() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockStore_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *MockStore_Expecter) Rollback() *MockStore_Rollback_Call {
	return &MockStore_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *MockStore_Rollback_Call) Run(run func()) *MockStore_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Rollback_Call) Return(err error) *MockStore_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Rollback_Call) RunAndReturn(run func() error) *MockStore_Rollback_Call {
	_c.Call.Return(run)
	return _c
}
