all: false
dir: '{{.InterfaceDir}}'
filename: '{{.InterfaceName | lower}}.go'
structname: 'Mock{{.InterfaceName}}'
pkgname: 'mocks'
recursive: false
packages:
  github.com/ofstudio/voxify/internal/domain:
    config:
      dir: './internal/mocks'
    interfaces:
      FeedBuilder:
      EpisodeDownloader:
      Platform:
      EventBus:
      Store:
