all: false
dir: '{{.InterfaceDir}}'
filename: '{{.InterfaceName | lower}}.go'
structname: 'Mock{{.InterfaceName}}'
pkgname: 'mocks'
recursive: false
packages:
  github.com/ofstudio/voxify/internal/store:
    config:
      dir: './internal/mocks'
    interfaces:
      Store:
  github.com/ofstudio/voxify/internal/services:
    config:
      dir: './internal/mocks'
    interfaces:
      Platform:
      Downloader:
      Feeder:
