package config

import (
	"time"

	"github.com/ofstudio/voxify/internal/entities"
)

// Default returns default configuration
func Default() Config {
	return Config{
		DB: DB{
			Version: 1,
		},
		Settings: Settings{
			DownloadTimeout: 1 * time.Hour,
			YtDlpPath:       "yt-dlp",
			FFMpegPath:      "ffmpeg",
			ThumbnailSize:   3000,
			DownloadFormat:  entities.DownloadMp3,
			DownloadQuality: "192k",
			FeedFileName:    "rss.xml",
			FeedTitle:       "Voxify Podcast",
			FeedDescription: "This is a podcast feed generated by Voxify - https://github.com/ofstudio/voxify",
			FeedLink:        "https://github.com/ofstudio/voxify",
		},
	}
}
